### ISSUE TITLE
In Figma App (OSX) Maps are very low resolution

### ISSUE THREAD

**Issue by dlbone** [kawamurakazushi/figma-map-maker#21]
On export and preview in Figma both MapBox and Google Map generated images are low resolution both in the preview and in export. The size of the rectangle doesn't change this resolution.

**Comment by kawamurakazushi** [comment]
@dlbone Thanks for opening an issue!
Should be able to export higher resolution image now!

**Comment by dlbone** [comment]
@kawamurakazushi That was fast! Thanks, I can see it in Figma already
